services:

  java_db:
    container_name: java_db
    image: postgres:15
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airtek_channels_java
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  java_app:
    container_name: java_app
    image: erick/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/airtek_channels_java
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db

volumes:
  pgdata: {}
